### ISSUE TITLE
视频资源下载前后显示不匹配

### ISSUE THREAD

**Issue by zinbers** [ThreeZT/BugReport#17]
![11](https://user-images.githubusercontent.com/4044560/27021648-64d49b94-4f7c-11e7-9f4e-5d0baac0e38c.png)
![12](https://user-images.githubusercontent.com/4044560/27021661-7273360c-4f7c-11e7-968a-b49b18a805ee.png)

**Comment by ThreeZT** [comment]
是所有的下载页面显示的都和其他页面显示的不一样吗，这里应该是Mac平台进制转换本身对的问题，你可以看一下同样的问题在mac平台上是比winnows上大

**Comment by zinbers** [comment]
对的。应该是这个问题。

**Comment by zinbers** [comment]
那这里可以优化一下显示，要不然别人会误以为下载文件有错。只要显示一致就行。

**Comment by ThreeZT** [comment]
一个是后台接口给的数据，一个是实际下载是获取的文件大小，要是统一用后台返回的大小你又会发现下载后的文件大小和显示的大小不一样

**Comment by zinbers** [comment]
那把这个问题弄到FAQ里面吧
